"""plan_template unique(name,version)

Revision ID: 31dfc5245d2f
Revises: 38f12a115426
Create Date: 2026-06-19 22:30:36.185390
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "31dfc5245d2f"
down_revision: str | None = "38f12a115426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_plan_template_name_version", "plan_template", ["name", "version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_plan_template_name_version", "plan_template", type_="unique")
    # ### end Alembic commands ###
