"""m1 full schema

Revision ID: f968dc6adc21
Revises: 23b806311f63
Create Date: 2026-06-18 10:52:42.317419
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f968dc6adc21"
down_revision: str | None = "23b806311f63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table(
        "app_user",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled')", name=op.f("ck_app_user_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "capability",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_capability")),
    )
    op.create_table(
        "model_catalog",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("litellm_name", sa.Text(), nullable=True),
        sa.Column("capabilities", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("price_in", sa.Numeric(), nullable=True),
        sa.Column("price_out", sa.Numeric(), nullable=True),
        sa.Column("connector", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_catalog")),
    )
    op.create_table(
        "plan_template",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("dag_skeleton", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_template")),
    )
    op.create_table(
        "scenario_preset",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("required_capabilities", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_preset")),
        sa.UniqueConstraint("name", "version", name="name_version"),
    )
    op.create_table(
        "auth_session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_hash", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_auth_session_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_session")),
    )
    op.create_index(op.f("ix_auth_session_user_id"), "auth_session", ["user_id"], unique=False)
    op.create_table(
        "credential",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("dek_wrapped", sa.LargeBinary(), nullable=False),
        sa.Column("budget_cents", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"], ["model_catalog.id"], name=op.f("fk_credential_model_id_model_catalog")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_credential_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "model_id", name=op.f("pk_credential")),
    )
    op.create_table(
        "org",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("charter", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("budget_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "shared_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "policies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('active','archived')", name=op.f("ck_org_status")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["app_user.id"], name=op.f("fk_org_owner_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org")),
    )
    op.create_table(
        "approval",
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("assignee", sa.Uuid(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('plan','dangerous_action','provision_review','skill_review','rework')",
            name=op.f("ck_approval_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected')", name=op.f("ck_approval_status")
        ),
        sa.ForeignKeyConstraint(
            ["assignee"], ["app_user.id"], name=op.f("fk_approval_assignee_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["app_user.id"], name=op.f("fk_approval_decided_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_approval_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.create_index(op.f("ix_approval_org_id"), "approval", ["org_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_audit_log_org_id_org"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "memory",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("importance", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("confidence", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("decay_rate", sa.Float(), server_default="0.01", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_accessed", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "scope IN ('session','task','role','org')", name=op.f("ck_memory_scope")
        ),
        sa.CheckConstraint(
            "type IN ('factual','procedural','preference','event')", name=op.f("ck_memory_type")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_memory_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory")),
    )
    op.create_index(op.f("ix_memory_org_id"), "memory", ["org_id"], unique=False)
    op.create_index(
        "ix_memory_org_scope_ns", "memory", ["org_id", "scope", "namespace"], unique=False
    )
    op.create_table(
        "org_invite",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("role IN ('approver','member')", name=op.f("ck_org_invite_role")),
        sa.CheckConstraint(
            "status IN ('pending','accepted','revoked','expired')",
            name=op.f("ck_org_invite_status"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["app_user.id"], name=op.f("fk_org_invite_invited_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_org_invite_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_invite")),
    )
    op.create_index(op.f("ix_org_invite_org_id"), "org_invite", ["org_id"], unique=False)
    op.create_table(
        "org_member",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner','approver','member')", name=op.f("ck_org_member_role")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_org_member_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_org_member_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("org_id", "user_id", name=op.f("pk_org_member")),
    )
    op.create_table(
        "plan",
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("dag", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("estimated_cost_cents", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','approved','running','done','failed')", name=op.f("ck_plan_status")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_plan_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan")),
    )
    op.create_index(op.f("ix_plan_org_id"), "plan", ["org_id"], unique=False)
    op.create_table(
        "role",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_role_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_index(op.f("ix_role_org_id"), "role", ["org_id"], unique=False)
    op.create_table(
        "skill",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("trust", sa.Text(), server_default="private", nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("capability", sa.Text(), nullable=True),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column("owner_org_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("kind IN ('manual','tool')", name=op.f("ck_skill_kind")),
        sa.CheckConstraint(
            "status IN ('draft','published','deprecated')", name=op.f("ck_skill_status")
        ),
        sa.CheckConstraint(
            "trust IN ('official','verified','community','private')", name=op.f("ck_skill_trust")
        ),
        sa.ForeignKeyConstraint(
            ["owner_org_id"], ["org.id"], name=op.f("fk_skill_owner_org_id_org")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill")),
        sa.UniqueConstraint("name", name=op.f("uq_skill_name")),
    )
    op.create_table(
        "agent",
        sa.Column("role_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("current_version", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "source IN ('preset','generated','custom')", name=op.f("ck_agent_source")
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','suspended','archived')", name=op.f("ck_agent_status")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_agent_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_agent_role_id_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent")),
        sa.UniqueConstraint("org_id", "name", name="org_id_name"),
    )
    op.create_index(op.f("ix_agent_org_id"), "agent", ["org_id"], unique=False)
    op.create_table(
        "org_enabled_skill",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("enabled_by", sa.Uuid(), nullable=True),
        sa.Column("enabled_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["enabled_by"], ["app_user.id"], name=op.f("fk_org_enabled_skill_enabled_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_org_enabled_skill_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
            name=op.f("fk_org_enabled_skill_skill_id_skill"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "skill_id", name=op.f("pk_org_enabled_skill")),
    )
    op.create_table(
        "skill_version",
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("mcp_server", sa.Text(), nullable=True),
        sa.Column("tool", sa.Text(), nullable=True),
        sa.Column("io_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
            name=op.f("fk_skill_version_skill_id_skill"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_version")),
        sa.UniqueConstraint("skill_id", "version", name="skill_id_version"),
    )
    op.create_index(op.f("ix_skill_version_skill_id"), "skill_version", ["skill_id"], unique=False)
    op.create_table(
        "task_run",
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("temporal_workflow_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','paused','done','failed')",
            name=op.f("ck_task_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_task_run_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], name=op.f("fk_task_run_plan_id_plan")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_run")),
    )
    op.create_index(op.f("ix_task_run_org_id"), "task_run", ["org_id"], unique=False)
    op.create_table(
        "agent_capability",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.Text(), nullable=False),
        sa.Column("level", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_agent_capability_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_agent_capability_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("agent_id", "capability", name=op.f("pk_agent_capability")),
    )
    op.create_index(
        op.f("ix_agent_capability_org_id"), "agent_capability", ["org_id"], unique=False
    )
    op.create_table(
        "agent_version",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','published','deprecated')", name=op.f("ck_agent_version_status")
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_agent_version_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_agent_version_org_id_org"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_version")),
        sa.UniqueConstraint("agent_id", "version", name="agent_id_version"),
    )
    op.create_index(op.f("ix_agent_version_agent_id"), "agent_version", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_version_org_id"), "agent_version", ["org_id"], unique=False)
    op.create_table(
        "artifact_descriptor",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("node_id", sa.Text(), nullable=True),
        sa.Column("modality", sa.Text(), nullable=True),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("mime", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
            name=op.f("fk_artifact_descriptor_org_id_org"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task_run.id"], name=op.f("fk_artifact_descriptor_task_id_task_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_descriptor")),
    )
    op.create_index(
        op.f("ix_artifact_descriptor_org_id"), "artifact_descriptor", ["org_id"], unique=False
    )
    op.create_table(
        "result_envelope",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("node_id", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("needs_human", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent.id"], name=op.f("fk_result_envelope_agent_id_agent")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_result_envelope_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task_run.id"], name=op.f("fk_result_envelope_task_id_task_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_result_envelope")),
    )
    op.create_index(op.f("ix_result_envelope_org_id"), "result_envelope", ["org_id"], unique=False)
    op.create_table(
        "run_manifest",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("agents_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("skills_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("models_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("plan_version", sa.Text(), nullable=True),
        sa.Column("plan_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_run_manifest_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task_run.id"],
            name=op.f("fk_run_manifest_task_id_task_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_run_manifest")),
    )
    op.create_index(op.f("ix_run_manifest_org_id"), "run_manifest", ["org_id"], unique=False)
    op.create_table(
        "skill_invocation",
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_cents", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent.id"], name=op.f("fk_skill_invocation_agent_id_agent")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_skill_invocation_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skill.id"], name=op.f("fk_skill_invocation_skill_id_skill")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_invocation")),
    )
    op.create_index(
        op.f("ix_skill_invocation_org_id"), "skill_invocation", ["org_id"], unique=False
    )
    op.create_table(
        "trace_ref",
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("langfuse_trace_id", sa.Text(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["org.id"], name=op.f("fk_trace_ref_org_id_org"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], name=op.f("fk_trace_ref_plan_id_plan")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task_run.id"], name=op.f("fk_trace_ref_task_id_task_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_ref")),
    )
    op.create_index(op.f("ix_trace_ref_org_id"), "trace_ref", ["org_id"], unique=False)
    # ### end Alembic commands ###

    # ---- pgvector hnsw 索引（与模型 metadata 对齐）----
    for _t in ("memory", "capability", "scenario_preset", "plan_template"):
        op.create_index(
            f"ix_{_t}_embedding",
            _t,
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )

    # ---- 多租户 RLS（09§5 / ADR-0005）：组织级数据表启用行级隔离 ----
    # org/org_member/org_invite/audit_log 走应用层校验，不在此列。
    # ⚠ 实际生效需应用以非 superuser 角色连接（见 0b §3；非 superuser 角色 + 回归测试在批次4 接线）。
    rls_tables = (
        "role",
        "agent",
        "agent_version",
        "agent_capability",
        "org_enabled_skill",
        "memory",
        "result_envelope",
        "artifact_descriptor",
        "skill_invocation",
        "task_run",
        "plan",
        "run_manifest",
        "approval",
        "trace_ref",
    )
    for _t in rls_tables:
        op.execute(f"ALTER TABLE {_t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_t} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY org_isolation ON {_t} "
            "USING (org_id = current_setting('app.current_org', true)::uuid)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trace_ref_org_id"), table_name="trace_ref")
    op.drop_table("trace_ref")
    op.drop_index(op.f("ix_skill_invocation_org_id"), table_name="skill_invocation")
    op.drop_table("skill_invocation")
    op.drop_index(op.f("ix_run_manifest_org_id"), table_name="run_manifest")
    op.drop_table("run_manifest")
    op.drop_index(op.f("ix_result_envelope_org_id"), table_name="result_envelope")
    op.drop_table("result_envelope")
    op.drop_index(op.f("ix_artifact_descriptor_org_id"), table_name="artifact_descriptor")
    op.drop_table("artifact_descriptor")
    op.drop_index(op.f("ix_agent_version_org_id"), table_name="agent_version")
    op.drop_index(op.f("ix_agent_version_agent_id"), table_name="agent_version")
    op.drop_table("agent_version")
    op.drop_index(op.f("ix_agent_capability_org_id"), table_name="agent_capability")
    op.drop_table("agent_capability")
    op.drop_index(op.f("ix_task_run_org_id"), table_name="task_run")
    op.drop_table("task_run")
    op.drop_index(op.f("ix_skill_version_skill_id"), table_name="skill_version")
    op.drop_table("skill_version")
    op.drop_table("org_enabled_skill")
    op.drop_index(op.f("ix_agent_org_id"), table_name="agent")
    op.drop_table("agent")
    op.drop_table("skill")
    op.drop_index(op.f("ix_role_org_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_plan_org_id"), table_name="plan")
    op.drop_table("plan")
    op.drop_table("org_member")
    op.drop_index(op.f("ix_org_invite_org_id"), table_name="org_invite")
    op.drop_table("org_invite")
    op.drop_index("ix_memory_org_scope_ns", table_name="memory")
    op.drop_index(op.f("ix_memory_org_id"), table_name="memory")
    op.drop_table("memory")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_approval_org_id"), table_name="approval")
    op.drop_table("approval")
    op.drop_table("org")
    op.drop_table("credential")
    op.drop_index(op.f("ix_auth_session_user_id"), table_name="auth_session")
    op.drop_table("auth_session")
    op.drop_table("scenario_preset")
    op.drop_table("plan_template")
    op.drop_table("model_catalog")
    op.drop_table("capability")
    op.drop_table("app_user")
    # ### end Alembic commands ###
